env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  no-console: 0,
  linebreak-style: 0,
  import/extensions: 0 # FIXME: remove when rule will be adjusted for new nodejs version
}
